import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { Hospital, Shift } from "@/types";
import { UserProfile } from "@/stores/appStore";

interface GenerateReportParams {
    profile: UserProfile;
    month: Date;
    shifts: Shift[];
    hospitals: Hospital[];
}

export const generateMonthlyReport = ({
    profile,
    month,
    shifts,
    hospitals,
}: GenerateReportParams): Promise<string> => {
    return new Promise((resolve) => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;

        // --- Header ---
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text("Doctor Shift Manager", pageWidth / 2, 20, { align: "center" });

        doc.setFontSize(16);
        doc.setTextColor(60, 60, 60);
        doc.text("Monthly Report", pageWidth / 2, 30, { align: "center" });

        // --- Doctor Info ---
        doc.setFontSize(12);
        doc.setTextColor(80, 80, 80);
        doc.text(`Doctor: ${profile.name}`, 14, 45);
        doc.text(`Title: ${profile.title}`, 14, 52);
        doc.text(`Period: ${format(month, "MMMM yyyy")}`, 14, 59);

        doc.text(
            `Date Generated: ${format(new Date(), "dd MMM yyyy, HH:mm")}`,
            pageWidth - 14,
            45,
            { align: "right" }
        );

        // --- Stats Calculation ---
        const totalShifts = shifts.length;
        const totalPatients = shifts.reduce((sum, s) => sum + s.casesCount, 0);
        const totalIncome = shifts.reduce((sum, s) => sum + s.totalEarnings, 0);

        // --- Stats Summary ---
        doc.setFillColor(245, 247, 250);
        doc.roundedRect(14, 65, pageWidth - 28, 25, 3, 3, "F");

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("Total Shifts", 30, 73, { align: "center" });
        doc.text("Total Patients", pageWidth / 2, 73, { align: "center" });
        doc.text("Total Income", pageWidth - 30, 73, { align: "center" });

        doc.setFontSize(14);
        doc.setTextColor(40, 40, 40);
        doc.setFont("helvetica", "bold");
        doc.text(totalShifts.toString(), 30, 83, { align: "center" });
        doc.text(totalPatients.toString(), pageWidth / 2, 83, { align: "center" });
        doc.text(`${totalIncome.toLocaleString()} EGP`, pageWidth - 30, 83, { align: "center" });
        doc.setFont("helvetica", "normal");

        // --- Table Data ---
        const tableData = shifts.map((s) => {
            const hospital = hospitals.find((h) => h.id === s.hospitalId);
            return [
                format(new Date(s.date), "dd MMM (EEE)"),
                hospital?.name || "Unknown",
                s.casesCount.toString(),
                `${s.totalEarnings.toLocaleString()} EGP`,
            ];
        });

        // --- Table ---
        autoTable(doc, {
            startY: 100,
            head: [["Date", "Hospital", "Patients", "Income"]],
            body: tableData,
            theme: "grid",
            headStyles: { fillColor: [59, 130, 246] }, // Blue header
            foot: [["Total", "", totalPatients.toString(), `${totalIncome.toLocaleString()} EGP`]],
            footStyles: { fillColor: [240, 240, 240], textColor: [40, 40, 40], fontStyle: "bold" },
        });

        // --- Footer ---
        const finalY = (doc as any).lastAutoTable.finalY + 10;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by Doctor Shift Manager App", pageWidth / 2, finalY, {
            align: "center",
        });

        // Return Base64 string (without prefix for Capacitor)
        const base64 = doc.output("datauristring").split(",")[1];
        resolve(base64);
    });
};
